name: Add SubModules
on:
  workflow_dispatch:
jobs:
  remove_submodules:
    runs-on: ubuntu-latest
    steps:
      - name: Add Submodule
        uses: actions/checkout@v2.3.5
      - run: |
          git submodule add https://aur.archlinux.org/makepkg-optimize-mold.git
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Add submodules
