name: Add SubModules
on:
  workflow_dispatch:
jobs:
  remove_submodules:
    runs-on: ubuntu-latest
    steps:
      - name: Add Submodule
        uses: actions/checkout@v2.3.5
      - run: |
          git submodule add https://aur.archlinux.org/xampp.git
          cat <<EOF >> .github/workflows/build.yml
            build_xampp:
              runs-on: ubuntu-latest
              steps:
                - name: build slimjet for arch
                  uses: actions/checkout@v2.3.5
                  with:
                    submodules: 'true'
                - run: ls -al
                - id: makepkg
                  uses: JPratama7/arch-pkgbuild-builder@main
                  with:
                    target: 'pkgbuild'
                    pkgname: 'xampp'
                - uses: ncipollo/release-action@v1.8.10
                  with:
                    tag: "kernel"
                    allowUpdates: true
                    artifacts: "./*/*.zst"
                    token: ${{ secrets.GITHUB_TOKEN }}
          EOF
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Add submodules
