name: Builder
on:
  workflow_dispatch:
jobs:

  build_spotify_adblock_git:
    runs-on: ubuntu-latest
    container: archlinux:latest
    steps:
      - run: |
          pacman -Syu --noconfirm --needed git
      - name: build spotify-adblock-git for arch
        uses: actions/checkout@v2.3.5
        with:
          submodules: true
          fetch-depth: '50'
          token: ${{ secrets.GITHUB_TOKEN }}
      - id: makepkg
        uses: JPratama7/pkgbuild-action@master
        with:
          makepkgArgs: "--skippgpcheck"
          pkgdir: "spotify-adblock-git"
      - run: ls -lR
      - run: |
          pacman -Syu
          export GPG_TTY=$(tty)
          gpg --batch --gen-key <<EOF
          Key-Type: 1
          Key-Length: 2048
          Subkey-Type: 1
          Subkey-Length: 2048
          Name-Real: github-actions[bot]
          Name-Email: 41898282+github-actions[bot]@users.noreply.github.com
          Expire-Date: 0
          EOF
          cd spotify-adblock-git
          gpg --detach-sign *.zst
      - uses: ncipollo/release-action@v1.8.10
        with:
          allowUpdates: true
          tag: "latest"
          artifacts: "*/*.zst"
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: ncipollo/release-action@v1.8.10
        with:
          allowUpdates: true
          tag: "latest"
          artifacts: "*/*.sig"
          token: ${{ secrets.GITHUB_TOKEN }}
      


