name: Builder
on:
  push:
  workflow_dispatch:
jobs:

  # build_spotify_adblock_git:
  #   runs-on: ubuntu-latest
  #   container: archlinux:latest
  #   steps:
  #     - run: pacman -Syu --noconfirm --needed git
  #     - uses: actions/checkout@v2.3.5
  #       # with:
  #       #   submodules: true
  #       #   fetch-depth: '50'
  #       #   token: ${{ secrets.GITHUB_TOKEN }}
  #     - id: makepkg
  #       uses: JPratama7/pkgbuild-action@toolchain
  #       with:
  #         makepkgArgs: "--skippgpcheck"
  #         pkgdir: "llvm"

  #     - uses: ncipollo/release-action@v1.8.10
  #       with:
  #         allowUpdates: true
  #         tag: "latest"
  #         artifacts: "*/*.zst"
  #         token: ${{ secrets.GITHUB_TOKEN }}
  #     - uses: actions/upload-artifact@v2
  #       with:
  #         path: "*/*.zst"

  python:
    strategy:
      matrix:
        build: [thorium]
      fail-fast: false
    runs-on: ubuntu-latest
    container: archlinux:latest
    steps:
      - name: Build packages for arch
        uses: actions/checkout@v2.4.0
      # - run: |
      #     pacman -Syu --noconfirm --needed git
      #     cat /etc/makepkg.conf
        # with:
        #   repository: JPratama7/arch-builder
          
      # - uses: webiny/action-post-run@2.0.1
      #   id: post-run-command
      #   with:
      #     run: cat xf86-video-amdgpu/src/xf86-video-amdgpu-22.0.0/config.log
      # - run : | 
      #     git clone https://github.com/pyston/pyston.git
      #     cd pyston
      #     git describe --tags
      #     ls
        # with:
        #   submodules: true
        #   fetch-depth: '50'
        #   token: ${{ secrets.GITHUB_TOKEN }}
      - id: makepkg
        uses: JPratama7/pkgbuild-action@cpuv2
        with:
          makepkgArgs: "--skippgpcheck --skipchecksums"
          pkgdir:  ${{ matrix.build }}

      - uses: ncipollo/release-action@v1.8.10
        with:
          allowUpdates: true
          tag: "latest"
          artifacts: "*/*.zst"
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/upload-artifact@v2
        with:
          path: "*/*.zst"
      
  # create_db_file:
  #   needs: [build_spotify_adblock_git]
  #   runs-on: ubuntu-latest
  #   container: archlinux:latest
  #   steps:
  #     - name: Download artifact
  #       uses: dawidd6/action-download-artifact@v2
  #       with:
  #         # Optional, GitHub token, a Personal Access Token with `public_repo` scope if needed
  #         # Required, if artifact is from a different repo
  #         # Required, if repo is private a Personal Access Token with `repo` scope is needed
  #         github_token: ${{secrets.GITHUB_TOKEN}}
  #         # Required, workflow file name or ID
  #         workflow: build.yml
  #         # Optional, defaults to current repo
  #         repo: ${{github.repository}}
  #     - name: creating database
  #       run:  |
  #         repo-add arch-repository-jpratama7.db.tar
  #         repo-add arch-repository-jpratama7.db.tar *.pkg.tar.zst
  #         ls
  #     - uses: ncipollo/release-action@v1.8.10
  #       with:
  #         allowUpdates: true
  #         replacesArtifacts: true
  #         tag: "latest"
  #         artifacts: "./arch-repository-jpratama7.*"
  #         token: ${{ secrets.GITHUB_TOKEN }}

