name: Github Action Build PKGBUILD
on:
  push:
  workflow_dispatch:
jobs:
  
  clone_repo_aur:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - run: ls -al
      - name: clone aur
        run: |
          # deinit all submodules from .gitmodules
          git submodule deinit .

          # remove all submodules (`git rm`) from .gitmodules
          git submodule | cut -c43- | while read -r line; do (git rm "$line"); done

          # delete all submodule sections from .git/config (`git config --local --remove-section`) by fetching those from .git/config
          git config --local -l | grep submodule | sed -e 's/^\(submodule\.[^.]*\)\(.*\)/\1/g' | while read -r line; do (git config --local --remove-section "$line"); done

          # manually remove leftovers
          rm .gitmodules
          rm -rf .git/modules

          git submodule add https://aur.archlinux.org/slimjet.git slimjet
          git submodule add https://aur.archlinux.org/spotify-adblock-git.git spotify-adblock-git
          git submodule update --init
      - name: update file and push to remote
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add -A
          git commit -m "Update test.txt"
          git push --force




  build_spotify_adblock_git:
    needs: [clone_repo_aur]
    runs-on: ubuntu-latest
    steps:
      - name: build spotify-adblock-git for arch
        uses: actions/checkout@v2.3.4
        with:
          submodules: 'true'
      - id: makepkg
        uses: JPratama7/pkgbuild-action@master
        with:
          makepkgArgs: "--skippgpcheck"
          pkgdir: "spotify-adblock-git"
          aurDeps: "spotify"

      - uses: ncipollo/release-action@v1.8.10
        with:
          allowUpdates: true
          tag: "latest"
          artifacts: "./*/*.zst"
          token: ${{ secrets.GITHUB_TOKEN }}

  build_slimjet:
    needs: [clone_repo_aur]
    runs-on: ubuntu-latest
    steps:
      - name: build slimjet for arch
        uses: actions/checkout@v2.3.4
        with:
          submodules: 'true'
      - id: makepkg
        uses: edlanglois/pkgbuild-action@master
        with:
          makepkgArgs: "--skippgpcheck"
          pkgdir: "slimjet"
          # target: "pkgbuild"
          # pkgname: "slimjet"
      - uses: ncipollo/release-action@v1.8.10
        with:
          tag: "kernel"
          allowUpdates: true
          artifacts: "./*/*.zst"
          token: ${{ secrets.GITHUB_TOKEN }}


