name: Builder
on:
  push:
  workflow_dispatch:
jobs:

  build_spotify_adblock_git:
    runs-on: ubuntu-latest
    container: archlinux:latest
    steps:
      - run: pacman -Syu --noconfirm --needed git
      - uses: actions/checkout@v2.3.5
        with:
          submodules: true
          fetch-depth: '50'
          token: ${{ secrets.GITHUB_TOKEN }}
      - id: makepkg
        uses: JPratama7/pkgbuild-action@cpuv2
        with:
          makepkgArgs: "--skippgpcheck"
          pkgdir: "spotify-adblock-git"

      - uses: ncipollo/release-action@v1.8.10
        with:
          allowUpdates: true
          tag: "latest"
          artifacts: "*/*.zst"
          token: ${{ secrets.GITHUB_TOKEN }}
      # - uses: ncipollo/release-action@v1.8.10
      #   with:
      #     allowUpdates: true
      #     tag: "latest"
      #     artifacts: "*/*.sig"
      #     token: ${{ secrets.GITHUB_TOKEN }}
      
  create_db_file:
    needs: [build_spotify_adblock_git]
    runs-on: ubuntu-latest
    container: archlinux:latest
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: "*/*.zst"
      - name: creating database
        run:  |
          repo-add arch-repository-jpratama7.db.tar
          repo-add arch-repository-jpratama7.db.tar *.pkg.tar.zst
          ls
      - uses: ncipollo/release-action@v1.8.10
        with:
          allowUpdates: true
          replacesArtifacts: true
          tag: "latest"
          artifacts: "./arch-repository-jpratama7.*"
          token: ${{ secrets.GITHUB_TOKEN }}

