name: Builder
on:
  push:
  workflow_dispatch:
jobs:

  build_spotify_adblock_git:
    runs-on: ubuntu-latest
    container: archlinux:latest
    steps:
      - run: pacman -Syu --noconfirm --needed git
      - name: Configure GPG Key
        run: |
          echo -n "$GPG_SIGNING_KEY" | base64 --decode | gpg --import
          ls /etc/profile.d/perlbin.sh
        env:
          GPG_SIGNING_KEY: ${{ secrets.GPG }}
      - uses: actions/checkout@v2.3.5
        with:
          submodules: true
          fetch-depth: '50'
          token: ${{ secrets.GITHUB_TOKEN }}
      - id: makepkg
        uses: JPratama7/pkgbuild-action@cpuv2
        with:
          makepkgArgs: "--skippgpcheck"
          pkgdir: "xampp"
      - run: ls -lR
      - run: |
          cd spotify-adblock-git
          gpg --detach-sign *.zst
          ls -lR
      - run: |
          repo-add arch-repository-jpratama7.db.tar.gz
          repo-add arch-repository-jpratama7.db.tar.gz -s -v *.pkg.tar.zst
          ls -lR

      - uses: ncipollo/release-action@v1.8.10
        with:
          allowUpdates: true
          tag: "latest"
          artifacts: "*/*.zst, */*.sig"
          token: ${{ secrets.GITHUB_TOKEN }}
      # - uses: ncipollo/release-action@v1.8.10
      #   with:
      #     allowUpdates: true
      #     tag: "latest"
      #     artifacts: "*/*.sig"
      #     token: ${{ secrets.GITHUB_TOKEN }}
      


