name: Builder
on:
  workflow_dispatch:
jobs:

  build_spotify_adblock_git:
    runs-on: ubuntu-latest
    steps:
      - name: build spotify-adblock-git for arch
        uses: actions/checkout@v2.3.5
        with:
          submodules: 'true' 
      - id: makepkg
        uses: JPratama7/pkgbuild-action@mine
        with:
          makepkgArgs: "--skippgpcheck --sign"
          pkgdir: "spotify-adblock-git"
      - run: ls -lR
      - uses: ncipollo/release-action@v1.8.10
        with:
          allowUpdates: true
          tag: "latest"
          artifacts: "*/*.zst"
          token: ${{ secrets.GITHUB_TOKEN }}


