name: Github Action Build PKGBUILD
on:
  workflow_dispatch:
jobs:  
  build_xampp:
    runs-on: ubuntu-latest
    steps:
      - name: build spotify-adblock-git for arch
        uses: actions/checkout@v2.3.5
        with:
          submodules: 'true'
      - id: makepkg
        uses: JPratama7/pkgbuild-action@master
        with:
          pkgdir: 'xampp'
          makepkgArgs: '--skippgpcheck'

      - uses: softprops/action-gh-release@master
        with:
          files: |
            *.zst
          tag_name: latest
          token: ${{ secrets.GITHUB_TOKEN }}

  build_spotify_adblock_git:
    runs-on: ubuntu-latest
    steps:
      - name: build spotify-adblock-git for arch
        uses: actions/checkout@v2.3.5
        with:
          submodules: 'true'
      - id: makepkg
        uses: JPratama7/arch-pkgbuild-builder@main
        with:
          target: 'pkgbuild'
          pkgname: 'spotify-adblock-git'
          makepkgArgs: "--skippgpcheck"
          pkgdir: "spotify-adblock-git"
          aurDeps: true

      - uses: softprops/action-gh-release@master
        with:
          files: |
            *.zst
          tag_name: latest
          token: ${{ secrets.GITHUB_TOKEN }}

  build_slimjet:
    runs-on: ubuntu-latest
    steps:
      - name: build slimjet for arch
        uses: actions/checkout@v2.3.5
        with:
          submodules: 'true'
      - id: makepkg
        uses: JPratama7/pkgbuild-action@master
        with:
          makepkgArgs: "--skippgpcheck"
          pkgdir: "slimjet"
          # target: "pkgbuild"
          # pkgname: "slimjet"
      - uses: softprops/action-gh-release@master
        with:
          files: |
            *.zst
          tag_name: latest
          token: ${{ secrets.GITHUB_TOKEN }}
