name: Github Action Build PKGBUILD
on:
  workflow_dispatch:
jobs:  
  build_xampp:
    runs-on: ubuntu-latest
    steps:
      - name: build slimjet for arch
        uses: actions/checkout@v2.3.5
        with:
          submodules: 'true'
      - id: makepkg
        uses: JPratama7/pkgbuild-action@master
        with:
          target: 'pkgbuild'
          pkgname: 'xampp'
      - uses: ncipollo/release-action@v1.8.10
        with:
          allowUpdates: true
          tag: "latest"
          artifacts: "./*/*.zst.sig"
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: ncipollo/release-action@v1.8.10
        with:
          allowUpdates: true
          tag: "latest"
          artifacts: "./*/*.zst"
          token: ${{ secrets.GITHUB_TOKEN }}
