name: Github Action Build PKGBUILD
on:
  push:
  workflow_dispatch:
jobs:
  
  clone_repo_aur:
    runs-on: ubuntu-latest
    steps:
      - name: clone aur
        run: |
          git clone https://aur.archlinux.org/slimjet.git
      - run: cd slimjet
      - name: run git commit
        uses: stefanzweifel/git-auto-commit-action@v4

  build_slimjet:
    needs: [clone_repo_aur]
    runs-on: ubuntu-latest
    steps:
      - name: build slimjet for arch
        uses: actions/checkout@v2.3.4
      - id: makepkg
        uses: edlanglois/pkgbuild-action@master
        with:
          makepkgArgs: "--skippgpcheck"
          pkgdir: "slimjet"
          # target: "pkgbuild"
          # pkgname: "slimjet"
      - uses: ncipollo/release-action@v1.8.10
        with:
          tag: "kernel"
          allowUpdates: true
          artifacts: "./*/*.zst"
          token: ${{ secrets.GITHUB_TOKEN }}


