name: Github Action Build PKGBUILD
on:
  push:
  workflow_dispatch:
jobs:
  
  clone_repo_aur:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - run: ls -al
      - run: |
          shopt -u dotglob
          rm *
          shopt -s dotglob
      - run: ls -al
      - name: clone aur
        run: |
          git clone https://aur.archlinux.org/slimjet.git
          git clone https://aur.archlinux.org/spotify-adblock-git.git
      - name: run git commit
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          add_options: '-A'




  build_spotify_adblock_git:
    needs: [clone_repo_aur]
    runs-on: ubuntu-latest
    steps:
      - name: build spotify-adblock-git for arch
        uses: actions/checkout@v2.3.4
      - id: makepkg
        uses: JPratama7/pkgbuild-action@master
        with:
          makepkgArgs: "--skippgpcheck"
          pkgdir: "spotify-adblock-git"
          aurDeps: "spotify"

      - uses: ncipollo/release-action@v1.8.10
        with:
          allowUpdates: true
          tag: "latest"
          artifacts: "./*/*.zst"
          token: ${{ secrets.GITHUB_TOKEN }}

  build_slimjet:
    needs: [clone_repo_aur]
    runs-on: ubuntu-latest
    steps:
      - name: build slimjet for arch
        uses: actions/checkout@v2.3.4
      - id: makepkg
        uses: edlanglois/pkgbuild-action@master
        with:
          makepkgArgs: "--skippgpcheck"
          pkgdir: "slimjet"
          # target: "pkgbuild"
          # pkgname: "slimjet"
      - uses: ncipollo/release-action@v1.8.10
        with:
          tag: "kernel"
          allowUpdates: true
          artifacts: "./*/*.zst"
          token: ${{ secrets.GITHUB_TOKEN }}


