name: Github Action Build PKGBUILD
on:
  workflow_dispatch:
jobs:  
#   build_spotify_adblock_git:
#     runs-on: ubuntu-latest
#     steps:
#       - name: build spotify-adblock-git for arch
#         uses: actions/checkout@v2.3.5
#         with:
#           submodules: 'true'
#       - id: makepkg
#         uses: JPratama7/arch-pkgbuild-builder@main
#         with:
#           target: 'pkgbuild'
#           pkgname: 'spotify-adblock-git'
# #           makepkgArgs: "--skippgpcheck"
# #           pkgdir: "spotify-adblock-git"
# #           aurDeps: true

#       - uses: ncipollo/release-action@v1.8.10
#         with:
#           allowUpdates: true
#           tag: "latest"
#           artifacts: "./*/*.zst"
#           token: ${{ secrets.GITHUB_TOKEN }}

#   build_slimjet:
#     runs-on: ubuntu-latest
#     steps:
#       - name: build slimjet for arch
#         uses: actions/checkout@v2.3.5
#         with:
#           submodules: 'true'
#       - id: makepkg
#         uses: JPratama7/pkgbuild-action@master
#         with:
#           makepkgArgs: "--skippgpcheck"
#           pkgdir: "slimjet"
#           # target: "pkgbuild"
#           # pkgname: "slimjet"
#       - uses: ncipollo/release-action@v1.8.10
#         with:
#           tag: "kernel"
#           allowUpdates: true
#           artifacts: "./*/*.zst"
#           token: ${{ secrets.GITHUB_TOKEN }}

  build_xampp:
    runs-on: ubuntu-latest
    steps:
      - name: build slimjet for arch
        uses: actions/checkout@v2.3.5
        with:
          submodules: 'true'
      - run: ls -al
      - id: makepkg
        uses: JPratama7/pkgbuild-action@main
        with:
          target: 'pkgbuild'
          pkgname: 'xampp'
      - uses: ncipollo/release-action@v1.8.10
        with:
          allowUpdates: true
          tag: "latest"
          artifacts: "./*/*.zst.sig"
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: ncipollo/release-action@v1.8.10
        with:
          allowUpdates: true
          tag: "latest"
          artifacts: "./*/*.zst"
          token: ${{ secrets.GITHUB_TOKEN }}
