name: Builder
on:
  workflow_dispatch:
jobs:

  build_spotify_adblock_git:
    runs-on: ubuntu-latest
    container: archlinux:latest
    steps:
      - run: |
          pacman -Syu --noconfirm --needed git
      - uses: actions/checkout@v2.3.5
        with:
          submodules: true
          fetch-depth: '50'
          token: ${{ secrets.GITHUB_TOKEN }}
      - id: makepkg
        uses: JPratama7/pkgbuild-action@master
        with:
          makepkgArgs: "--skippgpcheck"
          pkgdir: "spotify-adblock-git"
      - run: ls -lR
      - uses: actions/checkout@v2.3.5
        with:
          repository: JPratama7/gpgkey
          token: ${{ secrets.GITHUB_TOKEN }}
      - run: |
          pushd gpgkey
          gpg --import private.key
          popd
          cd spotify-adblock-git
          gpg --detach-sign *.zst
          ls -lR
      - uses: ncipollo/release-action@v1.8.10
        with:
          allowUpdates: true
          tag: "latest"
          artifacts: "*/*.zst"
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: ncipollo/release-action@v1.8.10
        with:
          allowUpdates: true
          tag: "latest"
          artifacts: "*/*.sig"
          token: ${{ secrets.GITHUB_TOKEN }}
      


