name: Test
on:
  push:
  workflow_dispatch:
jobs: 
  build_spotify_adblock_git: 
    runs-on: ubuntu-latest
    steps: 
       
      - uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH }}
          known_hosts: ${{ secrets.KNOWN_HOST }}        
      - run: "ssh -T git@${{ secrets.HOST }} || true"
      
      - run: |
            sudo apt-get update && apt-get upgrade
            sudo apt-get install git-lfs
            git clone git@gitlab.com:josepratama080/arch-repository.git
      - run: ls -lR
      - run: |
            git config --global user.email "josepratama080@gmail.com"
            git config --global user.name "josepratama080"
      - uses: robinraju/release-downloader@v1.2
        with: 
          fileName: "*"
          latest: true
          out-file-path: arch-repository
          repository: JPratama7/arch-builder
          tarBall: false
          zipBall: false
      - 
        run: |
            cd arch-repository
            git lfs install
            git lfs track "*.zst"
            git add .
            git commit -m 'add files'
            git push
